#!/usr/bin/env bash
# PreToolUse hook: block direct edits to config.json
# Reads tool input JSON from stdin; exit 2 to block + show message.

input=$(cat)

fp=$(echo "$input" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('file_path', d.get('path', '')))
except Exception:
    print('')
" 2>/dev/null)

if [[ "$fp" == *config.json ]]; then
    echo "BLOCK: config.json is runtime-generated by ShaderPlayer."
    echo "Edit shaderPresets via the UI or modify ConfigManager source instead."
    exit 2
fi

exit 0
