// ShaderCommon.hlsli — helper library injected ahead of every ShaderPlayer shader.
//
// Single source of truth. CMake embeds this file into the executable as a raw
// string literal (build/generated/ShaderCommonEmbedded.h, generated by
// tools/embed_hlsli.cmake) and tools/validate_shaders.py reads it directly, so
// the runtime compiler and the offline validator always see the same helpers.
// (CMake's file(WRITE) rewrites LF as CRLF, so the two copies differ in line
// endings only — the line count, and therefore the trailing #line 1, matches.)
//
// Every symbol is sp-prefixed (SP_ for macros) so it cannot collide with the
// per-shader helpers that already exist in the shipped set.
//
// fwidth-based helpers (spAAStep, spAALine) require the screen-space derivative
// of their argument, so they must not be called from inside divergent flow
// control — compute the field first, branch afterwards.

#define SP_PI  3.14159265358979
#define SP_TAU 6.28318530717959

// ---------------------------------------------------------------- tonemapping

// Narkowicz ACES fit. Punchy, saturated, sharp highlight roll-off.
float3 spTonemapACES(float3 x) {
    x = max(x, 0.0);
    return saturate((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14));
}

// ps_5_0 has no tanh intrinsic; the exp form is the identity
// tanh(x) = (1 - e^-2x) / (1 + e^-2x). Clamped so exp() cannot overflow fp32.
float spTanh1(float x) {
    x = clamp(x, -40.0, 40.0);
    float e = exp(-2.0 * x);
    return (1.0 - e) / (1.0 + e);
}

// ACES-like curve with darker mids and stronger colour. The natural partner for
// inverse-distance glow accumulation, which produces unbounded values.
float3 spTonemapTanh(float3 x) {
    return float3(spTanh1(x.r), spTanh1(x.g), spTanh1(x.b));
}

// Unreal 3 / Documents/Blog. Brightest of the three; sRGB gamma is baked in, so
// do NOT follow this with spLinearToSrgb.
float3 spTonemapUnreal(float3 x) {
    x = max(x, 0.0);
    return x / (x + 0.155) * 1.019;
}

// ------------------------------------------------------------- colour spaces

float3 spLinearToSrgb(float3 c) {
    c = max(c, 0.0);
    return lerp(12.92 * c, 1.055 * pow(max(c, 1e-8), 1.0 / 2.4) - 0.055, step(0.0031308, c));
}

float3 spSrgbToLinear(float3 c) {
    c = max(c, 0.0);
    return lerp(c / 12.92, pow((c + 0.055) / 1.055, 2.4), step(0.04045, c));
}

float3 spHsv2rgb(float3 c) {
    float3 p = abs(frac(c.xxx + float3(1.0, 2.0 / 3.0, 1.0 / 3.0)) * 6.0 - 3.0);
    return c.z * lerp(float3(1.0, 1.0, 1.0), saturate(p - 1.0), c.y);
}

float3 spRgb2hsv(float3 c) {
    float4 K = float4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);
    float4 p = lerp(float4(c.bg, K.wz), float4(c.gb, K.xy), step(c.b, c.g));
    float4 q = lerp(float4(p.xyw, c.r), float4(c.r, p.yzx), step(p.x, c.r));
    float d = q.x - min(q.w, q.y);
    return float3(abs(q.z + (q.w - q.y) / (6.0 * d + 1e-10)), d / (q.x + 1e-10), q.x);
}

// Rec.709 luminance.
float spLuma(float3 c) {
    return dot(c, float3(0.2126, 0.7152, 0.0722));
}

// Inigo Quilez cosine palette: continuous, cheap, and far better behaved than a
// piecewise lerp between stops. a = bias, b = amplitude, c = frequency, d = phase.
float3 spPalette(float t, float3 a, float3 b, float3 c, float3 d) {
    return a + b * cos(SP_TAU * (c * t + d));
}

// ------------------------------------------------------------------- hashing

// Dave Hoskins, "Hash without Sine". Deterministic, no trig, no texture fetch.
float spHash12(float2 p) {
    float3 p3 = frac(float3(p.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return frac((p3.x + p3.y) * p3.z);
}

float2 spHash22(float2 p) {
    float3 p3 = frac(float3(p.xyx) * float3(0.1031, 0.1030, 0.0973));
    p3 += dot(p3, p3.yzx + 33.33);
    return frac((p3.xx + p3.yz) * p3.zy);
}

float3 spHash33(float3 p) {
    p = frac(p * float3(0.1031, 0.1030, 0.0973));
    p += dot(p, p.yxz + 33.33);
    return frac((p.xxy + p.yxx) * p.zyx);
}

// Jimenez interleaved gradient noise. Takes a pixel coordinate (input.pos.xy),
// not a UV. Spectrally flat enough to dither with and cheaper than a hash.
float spIGN(float2 pixel) {
    return frac(52.9829189 * frac(dot(pixel, float2(0.06711056, 0.00583715))));
}

// Triangular-PDF dither. amount = 1.0/255.0 for an 8-bit target. Apply as the
// last operation before returning, after tonemapping.
float3 spDither(float3 col, float2 pixel, float amount) {
    float r0 = spHash12(pixel + 0.1);
    float r1 = spHash12(pixel + 7.3);
    return col + amount * (r0 + r1 - 1.0);
}

// ----------------------------------------------------------- band limiting/AA

// step(threshold, value) filtered over one pixel of the value's own footprint.
float spAAStep(float threshold, float value) {
    float w = max(fwidth(value), 1e-6) * 0.5;
    return smoothstep(threshold - w, threshold + w, value);
}

// 1 inside a line of half-width `width` about signedDist == 0, 0 outside.
float spAALine(float signedDist, float width) {
    float w = max(fwidth(signedDist), 1e-6) * 0.5;
    return 1.0 - smoothstep(width - w, width + w, abs(signedDist));
}

// Inigo Quilez: cos(x) attenuated by the average of the cosine over a footprint
// of width w (pass fwidth(x)). Stripes fade to flat grey instead of aliasing.
float spBandLimitedCos(float x, float w) {
    float h = 0.5 * w;
    return cos(x) * (abs(h) < 1e-4 ? 1.0 : sin(h) / h);
}

// ---------------------------------------------------------------- composition

// uv in [0,1]. Returns a multiplier: 1 at centre, falling to 1-amount at the
// corners. softness is the width of the falloff in normalised corner distance.
float spVignette(float2 uv, float amount, float softness) {
    float2 d = (uv - 0.5) * 2.0;
    float r = length(d) * 0.70710678;
    softness = max(softness, 1e-3);
    return lerp(1.0, 1.0 - smoothstep(1.0 - softness, 1.0, r), saturate(amount));
}

// Centred, aspect-corrected coordinates: (0,0) at centre, y spans [-1,1].
float2 spAspectUV(float2 uv, float2 res) {
    float2 p = uv * 2.0 - 1.0;
    p.x *= res.x / max(res.y, 1.0);
    return p;
}
